import { Saira } from 'next/font/google'
import './globals.css'
import Navbar from './components/navbar'
import Footer from './components/Footer'

const saira = Saira({ 
  subsets: ['latin'],
  weight:['100', '200', '300', '400', '500', '600', '700', '800', '900']
 })
export const metadata = {
  title: 'SAINCUBE',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={saira.className}>
        <Navbar/>
        {children}
        <Footer/>
      </body>
    </html>
  )
}
